apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: tracing-config
spec:
  tracing:
    samplingRate: "1" # This ensures that all traces are sampled
    zipkin:
      endpointAddress: "http://<otel-collector-service>:9411/api/v2/spans"
